<?php
<div id = "root" >
<div data - hooks = "app" >
<div data - hooks = "tool-bar" class="r5pCB" >
<div class="fkTq0" >
<a data - hooks = "logo" href = "https://www.wix.com" class="B0RNK NpV02" >
<span class="mUJ65" > wix . com</span ></a >
<div class="fkTq0" ><button data - hooks = "desktop-view" class="BGSjv _1y6LM" ><span class="yfxMt" > show desktop view </span ></button ><hr class="UIYr0" ><button data - hooks = "mobile-view" class="_41PDI " ><span class="yfxMt" > show mobile view </span ></button ></div ></div ><div class="fkTq0 undefined" ><p data - hooks = "tool-bar-title" class="DixmE" > Click edit and create your own amazing website </p ><a data - hooks = "info-view" class="R9DsC " tabindex = "0" role = "dialog" href = "#" > Read More </a ><a class="mfH9C" data - hooks = "editor-link" href = "https://manage.wix.com/edit-template/from-intro?originTemplateId=3e8b1a18-1c30-41cf-87ac-e18816787ea8&amp;editorSessionId=9CE45D86-1AE7-4A7B-3B41-EC0E69496B92" target = "_blank" tabindex = "0" > Edit this site </a ></div ></div ><div data - hooks = "template-demo" class="_7tRks" ><div data - hooks = "desktop-view" class="Nv5LU" ><iframe data - hooks = "desktop-iframe" src = "https://www.wix.com/demone2/nicol-rider" title = "Creative CV " width = "100%" height = "100%" class="GN17V" ></iframe ></div ></div ><div data - hooks = "info-pop-up" class="sO70G" ><div class="rKabk" ><button data - hooks = "card-close" class="+mRHt" ><span class="fOOD9" > close info popup </span ></button ><div class="hbnX-" ><h1 data - hooks = "card-title" class="+bcLj" > Creative CV - Website Template </h1 ><div class="SpKZ8" ><h3 data - hooks = "card-good-for-title" class="yppr7" > Good for:</
    h3 ><p data - hooks = "card-good-for" class="aPxEJ" > CVs, resumes and portfolios </p ></div ><div class="SpKZ8" ><h3 class="yppr7" > Description:</h3 ><p data - hooks = "card-description" class="aPxEJ" > Draw attention to your skills and experience with this professional template . This is the perfect place to highlight your qualifications, show off past projects and give a little insight on what makes you so approachable and professional . Click "Edit" to take your talents online today!</p ></div ></div ><div class="x+HDB" ><a data - hooks = "card-editor-url" class="_72Zi0 DY-ee" target = "_blank" href = "https://manage.wix.com/edit-template/from-intro?originTemplateId=3e8b1a18-1c30-41cf-87ac-e18816787ea8&amp;editorSessionId=9CE45D86-1AE7-4A7B-3B41-EC0E69496B92" > Edit Now </a ></div ></div ></div ></div ></div >

